### ISSUE TITLE
Local doesn't match deployed version

### ISSUE THREAD

**Issue by MrBrN197** [virag-ky/Tic-Tac-Toe#3]
I noticed the website version looks different from the local version. which commit are you deploying to GH pages from.?
because currently, the local version doesn't work; so I'm confused as to how this is happening.

**Comment by virag-ky** [comment]
Hi, I'm using my main branch only. I'm not sure what is not working....

**Comment by virag-ky** [comment]
I just opened it in my VSCode, it's the same as the deployed version...

**Comment by MrBrN197** [comment]
that's interesting when I cloned it. the website didn't seem to be working. I'll look at it again and get back to you

**Comment by virag-ky** [comment]
OKay 👍🏻

**Comment by MrBrN197** [comment]
hey sorry, my bad. it's actually working on the local version.
